// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-tNMpDTaLh9zaN67FL21YQOmBbLxVKk0',
    appId: '1:557915456897:web:f9ea842637ba889edbd480',
    messagingSenderId: '557915456897',
    projectId: 'sensor-app-ab31b',
    authDomain: 'sensor-app-ab31b.firebaseapp.com',
    databaseURL: 'https://sensor-app-ab31b-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-app-ab31b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1wML_PnIXV5N6V4D1M5zBw_We9TUtLw',
    appId: '1:557915456897:android:b9a22bdff226a4e8dbd480',
    messagingSenderId: '557915456897',
    projectId: 'sensor-app-ab31b',
    databaseURL: 'https://sensor-app-ab31b-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-app-ab31b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrNXdDpptDpppK0NvAxngXg_wu8Wtg4VM',
    appId: '1:557915456897:ios:1f291427969de83fdbd480',
    messagingSenderId: '557915456897',
    projectId: 'sensor-app-ab31b',
    databaseURL: 'https://sensor-app-ab31b-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-app-ab31b.appspot.com',
    iosBundleId: 'com.example.sensorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrNXdDpptDpppK0NvAxngXg_wu8Wtg4VM',
    appId: '1:557915456897:ios:6c9cf3f6169345badbd480',
    messagingSenderId: '557915456897',
    projectId: 'sensor-app-ab31b',
    databaseURL: 'https://sensor-app-ab31b-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-app-ab31b.appspot.com',
    iosBundleId: 'com.example.sensorapp.RunnerTests',
  );
}
